# DashMonitor Prometheus configuration

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'dashmonitor'
    environment: 'development'

# Alert rules
rule_files:
  - 'alert_rules.yml'

# Scrape configurations
scrape_configs:
  # API monitoring metrics
  - job_name: 'dashmonitor-api'
    static_configs:
      - targets: ['api:8000']
        labels:
          service: 'api'
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'